/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as MixedbreadAI from "..";

export class BadRequestError extends errors.MixedbreadAIError {
    constructor(body: MixedbreadAI.BadRequestErrorBody) {
        super({
            message: "BadRequestError",
            statusCode: 400,
            body: body,
        });
        Object.setPrototypeOf(this, BadRequestError.prototype);
    }
}
