/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors";
import * as MixedbreadAI from "..";
export declare class ForbiddenError extends errors.MixedbreadAIError {
    constructor(body: MixedbreadAI.ForbiddenErrorBody);
}
