/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as MixedbreadAI from "..";

export class ForbiddenError extends errors.MixedbreadAIError {
    constructor(body: MixedbreadAI.ForbiddenErrorBody) {
        super({
            message: "ForbiddenError",
            statusCode: 403,
            body: body,
        });
        Object.setPrototypeOf(this, ForbiddenError.prototype);
    }
}
