/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as MixedbreadAI from "../index";

export class InternalServerError extends errors.MixedbreadAIError {
    constructor(body: MixedbreadAI.InternalError) {
        super({
            message: "InternalServerError",
            statusCode: 500,
            body: body,
        });
        Object.setPrototypeOf(this, InternalServerError.prototype);
    }
}
