/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors";
import * as MixedbreadAI from "..";
export declare class NotFoundError extends errors.MixedbreadAIError {
    constructor(body: MixedbreadAI.NotFoundErrorBody);
}
