/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as MixedbreadAI from "../index";

export class TooManyRequestsError extends errors.MixedbreadAIError {
    constructor(body: MixedbreadAI.TooManyRequestsErrorBody) {
        super({
            message: "TooManyRequestsError",
            statusCode: 429,
            body: body,
        });
        Object.setPrototypeOf(this, TooManyRequestsError.prototype);
    }
}
