/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors";
import * as MixedbreadAiApi from "..";
export declare class TooManyRequestsError extends errors.MixedbreadAiApiError {
    constructor(body: MixedbreadAiApi.TooManyRequestsErrorBody);
}
