"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MixedbreadAITimeoutError = void 0;
class MixedbreadAITimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, MixedbreadAITimeoutError.prototype);
    }
}
exports.MixedbreadAITimeoutError = MixedbreadAITimeoutError;
