/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class MixedbreadAITimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, MixedbreadAITimeoutError.prototype);
    }
}
