"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MixedbreadAiApiTimeoutError = void 0;
class MixedbreadAiApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, MixedbreadAiApiTimeoutError.prototype);
    }
}
exports.MixedbreadAiApiTimeoutError = MixedbreadAiApiTimeoutError;
