/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as MixedbreadAI from "../../../api/index";
import * as core from "../../../core";
import { MultiModalInput } from "../../types/MultiModalInput";
import { EmbeddingsRequestEncodingFormat } from "../../types/EmbeddingsRequestEncodingFormat";
import { TruncationStrategy } from "../../types/TruncationStrategy";

export const EmbeddingsRequest: core.serialization.Schema<
    serializers.EmbeddingsRequest.Raw,
    MixedbreadAI.EmbeddingsRequest
> = core.serialization.object({
    model: core.serialization.string(),
    input: MultiModalInput,
    normalized: core.serialization.boolean().optional(),
    encodingFormat: core.serialization.property("encoding_format", EmbeddingsRequestEncodingFormat.optional()),
    truncationStrategy: core.serialization.property("truncation_strategy", TruncationStrategy.optional()),
    dimensions: core.serialization.number().optional(),
    prompt: core.serialization.string().optional(),
});

export declare namespace EmbeddingsRequest {
    interface Raw {
        model: string;
        input: MultiModalInput.Raw;
        normalized?: boolean | null;
        encoding_format?: EmbeddingsRequestEncodingFormat.Raw | null;
        truncation_strategy?: TruncationStrategy.Raw | null;
        dimensions?: number | null;
        prompt?: string | null;
    }
}
