/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../..";
import * as MixedbreadAiApi from "../../../api";
import * as core from "../../../core";
export declare const EmbeddingsRequest: core.serialization.Schema<serializers.EmbeddingsRequest.Raw, MixedbreadAiApi.EmbeddingsRequest>;
export declare namespace EmbeddingsRequest {
    interface Raw {
        model: string;
        input: serializers.Input.Raw;
        normalized?: boolean | null;
        encoding_format?: serializers.EmbeddingsRequestEncodingFormat.Raw | null;
        truncation_strategy?: serializers.TruncationStrategy.Raw | null;
        dimensions?: number | null;
        instruction?: string | null;
        texts?: string[] | null;
        prompt?: string | null;
    }
}
