/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as MixedbreadAI from "../../../api/index";
import * as core from "../../../core";
import { Query } from "../../types/Query";
import { MultiModalRerankingInput } from "../../types/MultiModalRerankingInput";

export const RerankingRequest: core.serialization.Schema<
    serializers.RerankingRequest.Raw,
    MixedbreadAI.RerankingRequest
> = core.serialization.object({
    model: core.serialization.string().optional(),
    query: Query,
    input: MultiModalRerankingInput,
    rankFields: core.serialization.property(
        "rank_fields",
        core.serialization.list(core.serialization.string()).optional()
    ),
    topK: core.serialization.property("top_k", core.serialization.number().optional()),
    returnInput: core.serialization.property("return_input", core.serialization.boolean().optional()),
});

export declare namespace RerankingRequest {
    interface Raw {
        model?: string | null;
        query: Query.Raw;
        input: MultiModalRerankingInput.Raw;
        rank_fields?: string[] | null;
        top_k?: number | null;
        return_input?: boolean | null;
    }
}
