/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import * as MixedbreadAI from "../../../api";
import * as core from "../../../core";

export const RerankingRequest: core.serialization.Schema<
    serializers.RerankingRequest.Raw,
    MixedbreadAI.RerankingRequest
> = core.serialization.object({
    input: core.serialization.list(core.serialization.lazyObject(async () => (await import("../..")).TextDocument)),
    model: core.serialization.string(),
    query: core.serialization.lazyObject(async () => (await import("../..")).TextDocument),
    returnInput: core.serialization.property("return_input", core.serialization.boolean().optional()),
    topK: core.serialization.property("top_k", core.serialization.number().optional()),
});

export declare namespace RerankingRequest {
    interface Raw {
        input: serializers.TextDocument.Raw[];
        model: string;
        query: serializers.TextDocument.Raw;
        return_input?: boolean | null;
        top_k?: number | null;
    }
}
