/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "../index";

/**
 * The created embeddings.
 */
export type Data = MixedbreadAI.Embedding[] | MixedbreadAI.MultipleEncodingsEmbedding[];
