/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MixedbreadAiApi from "..";
/**
 * The created embeddings
 */
export declare type Data = MixedbreadAiApi.Embedding[] | MixedbreadAiApi.MultiEncodingsEmbedding[];
