/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MixedbreadAI from "..";
/**
 * The created embeddings
 */
export declare type Data = MixedbreadAI.Embedding[] | MixedbreadAI.MultipleEncodingsEmbedding[];
