/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "../index";

export interface Embedding {
    /** The encoded embedding. */
    embedding: MixedbreadAI.EmbeddingItem;
    /** The index of the embedding. */
    index: number;
    /** The object type of the embedding. */
    object: "embedding";
}
