/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MixedbreadAiApi from "..";
export interface EmbeddingsResponse {
    /** The usage of the model */
    usage: MixedbreadAiApi.Usage;
    /** The model used */
    model: string;
    /** The created embeddings */
    data: MixedbreadAiApi.Data;
    /** The object type of the response */
    object?: MixedbreadAiApi.ObjectType;
    /** Whether the embeddings are normalized */
    normalized: boolean;
    encodingFormat: MixedbreadAiApi.EmbeddingsResponseEncodingFormat;
    dimensions?: number;
}
