/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MixedbreadAI from "..";
export declare type EmbeddingsResponseEncodingFormat = 
/**
 * The encoding format of the embeddings */
MixedbreadAI.EncodingFormat
/**
 * The encoding formats of the embeddings */
 | MixedbreadAI.EncodingFormat[];
