/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "..";

export interface EmbeddingsResponse {
    /** The created embeddings */
    data: MixedbreadAI.Data;
    dimensions?: number;
    encodingFormat: MixedbreadAI.EmbeddingsResponseEncodingFormat;
    /** The model used */
    model: string;
    /** Whether the embeddings are normalized */
    normalized: boolean;
    /** The object type of the response */
    object?: MixedbreadAI.ObjectType;
    /** The usage of the model */
    usage: MixedbreadAI.Usage;
}
