/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "../index";

export interface EmbeddingsResponse {
    /** The usage of the model */
    usage: MixedbreadAI.Usage;
    /** The model used */
    model: string;
    /** The created embeddings. */
    data: MixedbreadAI.Data;
    /** The object type of the response */
    object?: MixedbreadAI.ObjectType;
    /** Whether the embeddings are normalized. */
    normalized: boolean;
    encodingFormat: MixedbreadAI.EmbeddingsResponseEncodingFormat;
    /** The number of dimensions used for the embeddings. */
    dimensions?: number;
}
