/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "..";

export interface Embedding {
    embedding: MixedbreadAI.EmbeddingItem;
    /** The index of the embedding */
    index: number;
    /** The object type of the embedding */
    object?: MixedbreadAI.ObjectType;
}
