/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MixedbreadAiApi from "..";
export declare type EmbeddingsRequestEncodingFormat = 
/**
 * The encoding format of the embeddings */
MixedbreadAiApi.EncodingFormat
/**
 * The encoding formats of the embeddings */
 | MixedbreadAiApi.EncodingFormat[];
