/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "..";

export interface Embedding {
    /** The encoded embedding. */
    embedding: MixedbreadAI.EmbeddingItem;
    /** The index of the embedding. */
    index: number;
    object: "embedding";
}
