/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MixedbreadAiApi from "..";
export interface Embedding {
    /** The encoded embedding data by encoding format. */
    embedding: number[];
    /** The index of the embedding */
    index: number;
    /** The object type of the embedding */
    object?: MixedbreadAiApi.ObjectType;
}
