/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EncodingFormat = "float" | "base64" | "binary" | "ubinary" | "int8" | "uint8";

export const EncodingFormat = {
    Float: "float",
    Base64: "base64",
    Binary: "binary",
    Ubinary: "ubinary",
    Int8: "int8",
    Uint8: "uint8",
} as const;
