/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type EncodingFormat = "float" | "base64" | "binary" | "ubinary" | "int8" | "uint8";
export declare const EncodingFormat: {
    readonly Float: "float";
    readonly Base64: "base64";
    readonly Binary: "binary";
    readonly Ubinary: "ubinary";
    readonly Int8: "int8";
    readonly Uint8: "uint8";
};
