"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EncodingFormat = void 0;
exports.EncodingFormat = {
    Float: "float",
    Base64: "base64",
    Binary: "binary",
    Ubinary: "ubinary",
    Int8: "int8",
    Uint8: "uint8",
};
