/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MixedbreadAiApi from "..";
export declare type Input = 
/**
 * The input document to create embeddings for */
string
/**
 * The input document to create embeddings for */
 | string[]
/**
 * The input document to create embeddings for */
 | MixedbreadAiApi.TextDocument
/**
 * The input documents to create embeddings for */
 | MixedbreadAiApi.TextDocument[];
