/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MixedbreadAiApi from "..";
export interface InternalError {
    type?: "server_error";
    url?: string;
    message?: string;
    details?: MixedbreadAiApi.MxbaiWebErrorDetails;
}
