/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "..";

export interface InvalidMatryoshkaDimensionsError {
    type?: "invalid_matryoshka_dimensions_error";
    url?: string;
    message?: string;
    details?: MixedbreadAI.MxbaiApiErrorDetails;
}
