/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MixedbreadAiApi from "..";
export interface InvalidMatryoshkaModelError {
    type?: "invalid_matryoshka_model_error";
    url?: string;
    message?: string;
    details?: MixedbreadAiApi.MxbaiWebErrorDetails;
}
