/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MixedbreadAiApi from "..";
export interface MultiEncodingsEmbedding {
    /** The encoded embedding data by encoding format. Returned, if more than one encoding format is used. */
    embedding: Record<string, MixedbreadAiApi.MultiEncodingsEmbeddingEmbeddingValue>;
    /** The index of the embedding */
    index: number;
    /** The object type of the embedding */
    object?: MixedbreadAiApi.ObjectType;
}
