/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MultipleEncodingsEmbeddingItem {
    float?: number[];
    int8?: number[];
    uint8?: number[];
    binary?: number[];
    ubinary?: number[];
    base64?: string[];
}
