/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "..";

export interface MultipleEncodingsEmbedding {
    /** The encoded embedding data by encoding format. Returned, if more than one encoding format is used. */
    embedding: MixedbreadAI.MultipleEncodingsEmbeddingItem;
    /** The index of the embedding. */
    index: number;
    object: "embedding_dict";
}
