/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MultiModalRerankingInput =
    /**
     * The text input documents to rerank. */
    | string[]
    /**
     * The JSON inputs to rerank. */
    | Record<string, unknown>[];
