/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "../index";

export type MultiModalInput =
    /**
     * The text input document to create embeddings for. */
    | string
    /**
     * The text input documents to create embeddings for. */
    | string[]
    /**
     * The text input document to create embeddings for. */
    | MixedbreadAI.TextDocument
    /**
     * The text input documents to create embeddings for. */
    | MixedbreadAI.TextDocument[];
