/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MultipleEncodingsEmbeddingItem {
    base64: string[];
    binary: number[];
    float: number[];
    int8: number[];
    ubinary: number[];
    uint8: number[];
}
