/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "..";

export interface MxbaiApiError {
    details?: MixedbreadAI.MxbaiApiErrorDetails;
    message?: string;
    type?: string;
    url?: string;
}
