/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MixedbreadAiApi from "..";
export interface MxbaiWebError {
    type?: string;
    url?: string;
    message?: string;
    details?: MixedbreadAiApi.MxbaiWebErrorDetails;
}
