/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MixedbreadAI from "..";
export interface MxbaiWebError {
    details?: MixedbreadAI.MxbaiWebErrorDetails;
    message?: string;
    type?: string;
    url?: string;
}
