/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type ObjectType = "list" | "embedding" | "embedding_dict" | "text_document";
export declare const ObjectType: {
    readonly List: "list";
    readonly Embedding: "embedding";
    readonly EmbeddingDict: "embedding_dict";
    readonly TextDocument: "text_document";
};
