/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ObjectType = "list" | "embedding" | "embedding_dict" | "text_document";

export const ObjectType = {
    List: "list",
    Embedding: "embedding",
    EmbeddingDict: "embedding_dict",
    TextDocument: "text_document",
} as const;
