/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "../index";

/**
 * The query to rerank the documents.
 */
export type Query = MixedbreadAI.TextDocument | string;
