/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "..";

export interface RerankingResponse {
    /** The ranked documents */
    data: MixedbreadAI.RankedDocument[];
    /** The model used */
    model: string;
    /** The object type of the response */
    object?: MixedbreadAI.ObjectType;
    /** Whether to return the documents */
    returnInput: boolean;
    /** The number of documents to return */
    topK: number;
    /** The usage of the model */
    usage: MixedbreadAI.Usage;
}
