/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "../index";

export interface RerankingResponse {
    /** The usage of the model */
    usage: MixedbreadAI.Usage;
    /** The model used */
    model: string;
    /** The ranked documents. */
    data: MixedbreadAI.RankedDocument[];
    /** The object type of the response */
    object?: MixedbreadAI.ObjectType;
    /** The number of documents to return. */
    topK: number;
    /** Whether to return the documents. */
    returnInput: boolean;
}
