/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MixedbreadAiApi from "..";
export interface RerankingResponse {
    /** The usage of the model */
    usage: MixedbreadAiApi.Usage;
    /** The model used */
    model: string;
    /** The ranked documents */
    data: MixedbreadAiApi.RankedDocument[];
    /** The object type of the response */
    object?: MixedbreadAiApi.ObjectType;
    /** The number of documents to return */
    topK: number;
    /** Whether to return the documents */
    returnInput: boolean;
}
