/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TextDocument {
    /** The type of the document */
    type?: "text";
    /** The text to be processed */
    text: string;
}
