/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "../index";

export interface TooManyRequestsErrorBody {
    type?: "too_many_requests_error";
    url?: string;
    message?: string;
    details?: MixedbreadAI.MxbaiApiErrorDetails;
}
