/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "..";

export interface TooManyRequestsErrorBody {
    type?: "too_many_requests_error";
    details?: MixedbreadAI.MxbaiApiErrorDetails;
    message?: string;
    url?: string;
}
