/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Truncation strategies for sentence embeddings
 */
export declare type TruncationStrategy = "start" | "end" | "none";
export declare const TruncationStrategy: {
    readonly Start: "start";
    readonly End: "end";
    readonly None: "none";
};
