"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TruncationStrategy = void 0;
exports.TruncationStrategy = {
    Start: "start",
    End: "end",
    None: "none",
};
