/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as MixedbreadAiApi from "../..";
/**
 * @example
 *     {
 *         model: "model"
 *     }
 */
export interface EmbeddingsRequest {
    /** The model to use for creating embeddings */
    model: string;
    input: MixedbreadAiApi.Input;
    /** Whether to normalize the embeddings */
    normalized?: boolean;
    encodingFormat?: MixedbreadAiApi.EmbeddingsRequestEncodingFormat;
    /** The truncation strategy to use for the input */
    truncationStrategy?: MixedbreadAiApi.TruncationStrategy;
    dimensions?: number;
    instruction?: string;
    texts?: string[];
    prompt?: string;
}
