/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "../..";

/**
 * @example
 *     {
 *         model: "model",
 *         query: {
 *             text: "text"
 *         },
 *         input: ["input"],
 *         topK: 10,
 *         returnInput: false
 *     }
 */
export interface RerankingRequest {
    /** The model to use for reranking documents */
    model: string;
    /** The query to rerank the documents */
    query: MixedbreadAI.Query;
    input: MixedbreadAI.MultiModalRerankingInput;
    rankFields?: string[];
    /** The number of documents to return */
    topK?: number;
    /** Whether to return the documents */
    returnInput?: boolean;
}
