/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "../../index";

/**
 * @example
 *     {
 *         query: {
 *             text: "text"
 *         },
 *         input: ["Document 1", "Document 2"]
 *     }
 */
export interface RerankingRequest {
    /** The model to use for reranking documents. */
    model?: string;
    /** The query to rerank the documents. */
    query: MixedbreadAI.Query;
    input: MixedbreadAI.MultiModalRerankingInput;
    /** The fields of the documents to rank. */
    rankFields?: string[];
    /** The number of documents to return. */
    topK?: number;
    /** Whether to return the documents. */
    returnInput?: boolean;
}
