/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as MixedbreadAI from "../..";

/**
 * @example
 *     {
 *         input: [{
 *                 text: "text"
 *             }],
 *         model: "model",
 *         query: {
 *             text: "text"
 *         },
 *         returnInput: false,
 *         topK: 10
 *     }
 */
export interface RerankingRequest {
    /** The input documents to rerank */
    input: MixedbreadAI.TextDocument[];
    /** The model to use for creating embeddings */
    model: string;
    /** The query to rerank the documents */
    query: MixedbreadAI.TextDocument;
    /** Whether to return the documents */
    returnInput?: boolean;
    /** The number of documents to return */
    topK?: number;
}
