/* tslint:disable */
/* eslint-disable */
/**
 * mixedbread-ai
 * Discover how to convert text into embeddings with the Embeddings API. Ideal for NLP tasks like text similarity and clustering. Use top open source models or your own fine-tuned models.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EmbeddingsRequest,
  EmbeddingsResponse,
  ErrorResponse,
} from '../models/index';
import {
    EmbeddingsRequestFromJSON,
    EmbeddingsRequestToJSON,
    EmbeddingsResponseFromJSON,
    EmbeddingsResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index';

export interface EmbeddingsOperationRequest {
    embeddingsRequest: EmbeddingsRequest;
}

/**
 * MixedbreadAiApi - interface
 * 
 * @export
 * @interface MixedbreadAiApiInterface
 */
export interface MixedbreadAiApiInterface {
    /**
     * This endpoint allows you to post text data and receive embeddings in response. The embeddings are generated using the model specified in the request body.
     * @summary Create embeddings
     * @param {EmbeddingsRequest} embeddingsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MixedbreadAiApiInterface
     */
    embeddingsRaw(requestParameters: EmbeddingsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmbeddingsResponse>>;

    /**
     * This endpoint allows you to post text data and receive embeddings in response. The embeddings are generated using the model specified in the request body.
     * Create embeddings
     */
    embeddings(embeddingsRequest: EmbeddingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmbeddingsResponse>;

}

/**
 * 
 */
export class MixedbreadAiApi extends runtime.BaseAPI implements MixedbreadAiApiInterface {

    /**
     * This endpoint allows you to post text data and receive embeddings in response. The embeddings are generated using the model specified in the request body.
     * Create embeddings
     */
    async embeddingsRaw(requestParameters: EmbeddingsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmbeddingsResponse>> {
        if (requestParameters.embeddingsRequest === null || requestParameters.embeddingsRequest === undefined) {
            throw new runtime.RequiredError('embeddingsRequest','Required parameter requestParameters.embeddingsRequest was null or undefined when calling embeddings.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // MIXEDBREADAI_API_KEY authentication
        }

        const response = await this.request({
            path: `/v1/embeddings/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmbeddingsRequestToJSON(requestParameters.embeddingsRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmbeddingsResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint allows you to post text data and receive embeddings in response. The embeddings are generated using the model specified in the request body.
     * Create embeddings
     */
    async embeddings(embeddingsRequest: EmbeddingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmbeddingsResponse> {
        const response = await this.embeddingsRaw({ embeddingsRequest: embeddingsRequest }, initOverrides);
        return await response.value();
    }

}
