/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";
import { MxbaiApiErrorDetails } from "./MxbaiApiErrorDetails";

export const BadRequestErrorBody: core.serialization.ObjectSchema<
    serializers.BadRequestErrorBody.Raw,
    MixedbreadAI.BadRequestErrorBody
> = core.serialization.object({
    type: core.serialization.stringLiteral("bad_request_error").optional(),
    url: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
    details: MxbaiApiErrorDetails.optional(),
});

export declare namespace BadRequestErrorBody {
    interface Raw {
        type?: "bad_request_error" | null;
        url?: string | null;
        message?: string | null;
        details?: MxbaiApiErrorDetails.Raw | null;
    }
}
