/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";
import { Embedding } from "./Embedding";
import { MultipleEncodingsEmbedding } from "./MultipleEncodingsEmbedding";

export const Data: core.serialization.Schema<serializers.Data.Raw, MixedbreadAI.Data> =
    core.serialization.undiscriminatedUnion([
        core.serialization.list(Embedding),
        core.serialization.list(MultipleEncodingsEmbedding),
    ]);

export declare namespace Data {
    type Raw = Embedding.Raw[] | MultipleEncodingsEmbedding.Raw[];
}
