/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";

export const Data: core.serialization.Schema<serializers.Data.Raw, MixedbreadAI.Data> =
    core.serialization.undiscriminatedUnion([
        core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).Embedding)),
        core.serialization.list(
            core.serialization.lazyObject(async () => (await import("..")).MultipleEncodingsEmbedding)
        ),
    ]);

export declare namespace Data {
    type Raw = serializers.Embedding.Raw[] | serializers.MultipleEncodingsEmbedding.Raw[];
}
