/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const Data: core.serialization.Schema<serializers.Data.Raw, MixedbreadAiApi.Data>;
export declare namespace Data {
    type Raw = serializers.Embedding.Raw[] | serializers.MultiEncodingsEmbedding.Raw[];
}
