/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";
export declare const EmbeddingItem: core.serialization.Schema<serializers.EmbeddingItem.Raw, MixedbreadAI.EmbeddingItem>;
export declare namespace EmbeddingItem {
    type Raw = number[] | number[] | string;
}
