/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const EmbeddingsResponse: core.serialization.ObjectSchema<serializers.EmbeddingsResponse.Raw, MixedbreadAiApi.EmbeddingsResponse>;
export declare namespace EmbeddingsResponse {
    interface Raw {
        usage: serializers.Usage.Raw;
        model: string;
        data: serializers.Data.Raw;
        object?: serializers.ObjectType.Raw | null;
        normalized: boolean;
        encoding_format: serializers.EmbeddingsResponseEncodingFormat.Raw;
        dimensions?: number | null;
    }
}
