/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const EmbeddingsRequestEncodingFormat: core.serialization.Schema<serializers.EmbeddingsRequestEncodingFormat.Raw, MixedbreadAiApi.EmbeddingsRequestEncodingFormat>;
export declare namespace EmbeddingsRequestEncodingFormat {
    type Raw = serializers.EncodingFormat.Raw | serializers.EncodingFormat.Raw[];
}
