/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";
export declare const Embedding: core.serialization.ObjectSchema<serializers.Embedding.Raw, MixedbreadAI.Embedding>;
export declare namespace Embedding {
    interface Raw {
        embedding: serializers.EmbeddingItem.Raw;
        index: number;
        object?: serializers.ObjectType.Raw | null;
    }
}
