/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";
import { EncodingFormat } from "./EncodingFormat";

export const EmbeddingsRequestEncodingFormat: core.serialization.Schema<
    serializers.EmbeddingsRequestEncodingFormat.Raw,
    MixedbreadAI.EmbeddingsRequestEncodingFormat
> = core.serialization.undiscriminatedUnion([EncodingFormat, core.serialization.list(EncodingFormat)]);

export declare namespace EmbeddingsRequestEncodingFormat {
    type Raw = EncodingFormat.Raw | EncodingFormat.Raw[];
}
