/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const EmbeddingsResponseEncodingFormat: core.serialization.Schema<serializers.EmbeddingsResponseEncodingFormat.Raw, MixedbreadAiApi.EmbeddingsResponseEncodingFormat>;
export declare namespace EmbeddingsResponseEncodingFormat {
    type Raw = serializers.EncodingFormat.Raw | serializers.EncodingFormat.Raw[];
}
