/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";
import { EmbeddingItem } from "./EmbeddingItem";

export const Embedding: core.serialization.ObjectSchema<serializers.Embedding.Raw, MixedbreadAI.Embedding> =
    core.serialization.object({
        embedding: EmbeddingItem,
        index: core.serialization.number(),
        object: core.serialization.stringLiteral("embedding"),
    });

export declare namespace Embedding {
    interface Raw {
        embedding: EmbeddingItem.Raw;
        index: number;
        object: "embedding";
    }
}
