/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";
export declare const EncodingFormat: core.serialization.Schema<serializers.EncodingFormat.Raw, MixedbreadAI.EncodingFormat>;
export declare namespace EncodingFormat {
    type Raw = "float" | "base64" | "binary" | "ubinary" | "int8" | "uint8";
}
