/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";

export const EncodingFormat: core.serialization.Schema<serializers.EncodingFormat.Raw, MixedbreadAI.EncodingFormat> =
    core.serialization.enum_(["float", "base64", "binary", "ubinary", "int8", "uint8"]);

export declare namespace EncodingFormat {
    type Raw = "float" | "base64" | "binary" | "ubinary" | "int8" | "uint8";
}
