/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";
export declare const ForbiddenErrorBody: core.serialization.ObjectSchema<serializers.ForbiddenErrorBody.Raw, MixedbreadAI.ForbiddenErrorBody>;
export declare namespace ForbiddenErrorBody {
    interface Raw {
        type?: "forbidden_error" | null;
        details?: serializers.MxbaiWebErrorDetails.Raw | null;
        message?: string | null;
        url?: string | null;
    }
}
