/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const Input: core.serialization.Schema<serializers.Input.Raw, MixedbreadAiApi.Input>;
export declare namespace Input {
    type Raw = string | string[] | serializers.TextDocument.Raw | serializers.TextDocument.Raw[];
}
