/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const InternalError: core.serialization.ObjectSchema<serializers.InternalError.Raw, MixedbreadAiApi.InternalError>;
export declare namespace InternalError {
    interface Raw {
        type?: "server_error" | null;
        url?: string | null;
        message?: string | null;
        details?: serializers.MxbaiWebErrorDetails.Raw | null;
    }
}
