/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const InvalidMatryoshkaDimensionsError: core.serialization.ObjectSchema<serializers.InvalidMatryoshkaDimensionsError.Raw, MixedbreadAiApi.InvalidMatryoshkaDimensionsError>;
export declare namespace InvalidMatryoshkaDimensionsError {
    interface Raw {
        type?: "invalid_matryoshka_dimensions_error" | null;
        url?: string | null;
        message?: string | null;
        details?: serializers.MxbaiWebErrorDetails.Raw | null;
    }
}
