/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const InvalidMatryoshkaModelError: core.serialization.ObjectSchema<serializers.InvalidMatryoshkaModelError.Raw, MixedbreadAiApi.InvalidMatryoshkaModelError>;
export declare namespace InvalidMatryoshkaModelError {
    interface Raw {
        type?: "invalid_matryoshka_model_error" | null;
        url?: string | null;
        message?: string | null;
        details?: serializers.MxbaiWebErrorDetails.Raw | null;
    }
}
