/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";
import { MxbaiApiErrorDetails } from "./MxbaiApiErrorDetails";

export const InvalidMatryoshkaDimensionsError: core.serialization.ObjectSchema<
    serializers.InvalidMatryoshkaDimensionsError.Raw,
    MixedbreadAI.InvalidMatryoshkaDimensionsError
> = core.serialization.object({
    type: core.serialization.stringLiteral("invalid_matryoshka_dimensions_error").optional(),
    url: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
    details: MxbaiApiErrorDetails.optional(),
});

export declare namespace InvalidMatryoshkaDimensionsError {
    interface Raw {
        type?: "invalid_matryoshka_dimensions_error" | null;
        url?: string | null;
        message?: string | null;
        details?: MxbaiApiErrorDetails.Raw | null;
    }
}
