/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";

export const InvalidMatryoshkaDimensionsError: core.serialization.ObjectSchema<
    serializers.InvalidMatryoshkaDimensionsError.Raw,
    MixedbreadAI.InvalidMatryoshkaDimensionsError
> = core.serialization.object({
    type: core.serialization.stringLiteral("invalid_matryoshka_dimensions_error").optional(),
    url: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
    details: core.serialization.lazy(async () => (await import("..")).MxbaiApiErrorDetails).optional(),
});

export declare namespace InvalidMatryoshkaDimensionsError {
    interface Raw {
        type?: "invalid_matryoshka_dimensions_error" | null;
        url?: string | null;
        message?: string | null;
        details?: serializers.MxbaiApiErrorDetails.Raw | null;
    }
}
