/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";
export declare const ModelNotFoundError: core.serialization.ObjectSchema<serializers.ModelNotFoundError.Raw, MixedbreadAI.ModelNotFoundError>;
export declare namespace ModelNotFoundError {
    interface Raw {
        type?: "model_not_found_error" | null;
        details?: serializers.MxbaiWebErrorDetails.Raw | null;
        message?: string | null;
        url?: string | null;
    }
}
