/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";
import { MxbaiApiErrorDetails } from "./MxbaiApiErrorDetails";

export const ModelNotFoundError: core.serialization.ObjectSchema<
    serializers.ModelNotFoundError.Raw,
    MixedbreadAI.ModelNotFoundError
> = core.serialization.object({
    type: core.serialization.stringLiteral("model_not_found_error").optional(),
    url: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
    details: MxbaiApiErrorDetails.optional(),
});

export declare namespace ModelNotFoundError {
    interface Raw {
        type?: "model_not_found_error" | null;
        url?: string | null;
        message?: string | null;
        details?: MxbaiApiErrorDetails.Raw | null;
    }
}
