/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";
import { MultipleEncodingsEmbeddingItem } from "./MultipleEncodingsEmbeddingItem";

export const MultipleEncodingsEmbedding: core.serialization.ObjectSchema<
    serializers.MultipleEncodingsEmbedding.Raw,
    MixedbreadAI.MultipleEncodingsEmbedding
> = core.serialization.object({
    embedding: MultipleEncodingsEmbeddingItem,
    index: core.serialization.number(),
    object: core.serialization.stringLiteral("embedding_dict"),
});

export declare namespace MultipleEncodingsEmbedding {
    interface Raw {
        embedding: MultipleEncodingsEmbeddingItem.Raw;
        index: number;
        object: "embedding_dict";
    }
}
