/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";
import { TextDocument } from "./TextDocument";

export const MultiModalInput: core.serialization.Schema<serializers.MultiModalInput.Raw, MixedbreadAI.MultiModalInput> =
    core.serialization.undiscriminatedUnion([
        core.serialization.string(),
        core.serialization.list(core.serialization.string()),
        TextDocument,
        core.serialization.list(TextDocument),
    ]);

export declare namespace MultiModalInput {
    type Raw = string | string[] | TextDocument.Raw | TextDocument.Raw[];
}
