/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";

export const MultiModalInput: core.serialization.Schema<serializers.MultiModalInput.Raw, MixedbreadAI.MultiModalInput> =
    core.serialization.undiscriminatedUnion([
        core.serialization.string(),
        core.serialization.list(core.serialization.string()),
        core.serialization.lazyObject(async () => (await import("..")).TextDocument),
        core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).TextDocument)),
    ]);

export declare namespace MultiModalInput {
    type Raw = string | string[] | serializers.TextDocument.Raw | serializers.TextDocument.Raw[];
}
