/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const MultiEncodingsEmbeddingEmbeddingValue: core.serialization.Schema<serializers.MultiEncodingsEmbeddingEmbeddingValue.Raw, MixedbreadAiApi.MultiEncodingsEmbeddingEmbeddingValue>;
export declare namespace MultiEncodingsEmbeddingEmbeddingValue {
    type Raw = number[] | string | number[];
}
