/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";
export declare const MultipleEncodingsEmbedding: core.serialization.ObjectSchema<serializers.MultipleEncodingsEmbedding.Raw, MixedbreadAI.MultipleEncodingsEmbedding>;
export declare namespace MultipleEncodingsEmbedding {
    interface Raw {
        embedding: serializers.MultipleEncodingsEmbeddingItem.Raw;
        index: number;
        object?: serializers.ObjectType.Raw | null;
    }
}
