/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const MultiEncodingsEmbedding: core.serialization.ObjectSchema<serializers.MultiEncodingsEmbedding.Raw, MixedbreadAiApi.MultiEncodingsEmbedding>;
export declare namespace MultiEncodingsEmbedding {
    interface Raw {
        embedding: Record<string, serializers.MultiEncodingsEmbeddingEmbeddingValue.Raw>;
        index: number;
        object?: serializers.ObjectType.Raw | null;
    }
}
