/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const MxbaiWebErrorDetails: core.serialization.Schema<serializers.MxbaiWebErrorDetails.Raw, MixedbreadAiApi.MxbaiWebErrorDetails>;
export declare namespace MxbaiWebErrorDetails {
    type Raw = Record<string, unknown> | unknown[];
}
