/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";
export declare const MxbaiWebError: core.serialization.ObjectSchema<serializers.MxbaiWebError.Raw, MixedbreadAI.MxbaiWebError>;
export declare namespace MxbaiWebError {
    interface Raw {
        details?: serializers.MxbaiWebErrorDetails.Raw | null;
        message?: string | null;
        type?: string | null;
        url?: string | null;
    }
}
