/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";

export const MxbaiApiError: core.serialization.ObjectSchema<serializers.MxbaiApiError.Raw, MixedbreadAI.MxbaiApiError> =
    core.serialization.object({
        details: core.serialization.lazy(async () => (await import("..")).MxbaiApiErrorDetails).optional(),
        message: core.serialization.string().optional(),
        type: core.serialization.string().optional(),
        url: core.serialization.string().optional(),
    });

export declare namespace MxbaiApiError {
    interface Raw {
        details?: serializers.MxbaiApiErrorDetails.Raw | null;
        message?: string | null;
        type?: string | null;
        url?: string | null;
    }
}
