/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";
import { MxbaiApiErrorDetails } from "./MxbaiApiErrorDetails";

export const MxbaiApiError: core.serialization.ObjectSchema<serializers.MxbaiApiError.Raw, MixedbreadAI.MxbaiApiError> =
    core.serialization.object({
        type: core.serialization.string().optional(),
        url: core.serialization.string().optional(),
        message: core.serialization.string().optional(),
        details: MxbaiApiErrorDetails.optional(),
    });

export declare namespace MxbaiApiError {
    interface Raw {
        type?: string | null;
        url?: string | null;
        message?: string | null;
        details?: MxbaiApiErrorDetails.Raw | null;
    }
}
