/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";
export declare const NotFoundErrorBody: core.serialization.ObjectSchema<serializers.NotFoundErrorBody.Raw, MixedbreadAI.NotFoundErrorBody>;
export declare namespace NotFoundErrorBody {
    interface Raw {
        type?: "not_found_error" | null;
        details?: serializers.MxbaiWebErrorDetails.Raw | null;
        message?: string | null;
        url?: string | null;
    }
}
