/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";

export const ObjectType: core.serialization.Schema<serializers.ObjectType.Raw, MixedbreadAI.ObjectType> =
    core.serialization.enum_(["list", "embedding", "embedding_dict", "text_document"]);

export declare namespace ObjectType {
    type Raw = "list" | "embedding" | "embedding_dict" | "text_document";
}
