/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";
export declare const ObjectType: core.serialization.Schema<serializers.ObjectType.Raw, MixedbreadAI.ObjectType>;
export declare namespace ObjectType {
    type Raw = "list" | "embedding" | "embedding_dict" | "text_document";
}
