/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";

export const Query: core.serialization.Schema<serializers.Query.Raw, MixedbreadAI.Query> =
    core.serialization.undiscriminatedUnion([
        core.serialization.lazyObject(async () => (await import("..")).TextDocument),
        core.serialization.string(),
    ]);

export declare namespace Query {
    type Raw = serializers.TextDocument.Raw | string;
}
