/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";

export const RankedDocument: core.serialization.ObjectSchema<
    serializers.RankedDocument.Raw,
    MixedbreadAI.RankedDocument
> = core.serialization.object({
    index: core.serialization.number(),
    input: core.serialization.unknown(),
    object: core.serialization.lazy(async () => (await import("..")).ObjectType).optional(),
    score: core.serialization.number(),
});

export declare namespace RankedDocument {
    interface Raw {
        index: number;
        input?: unknown;
        object?: serializers.ObjectType.Raw | null;
        score: number;
    }
}
