/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const RankedDocument: core.serialization.ObjectSchema<serializers.RankedDocument.Raw, MixedbreadAiApi.RankedDocument>;
export declare namespace RankedDocument {
    interface Raw {
        index: number;
        score: number;
        input?: unknown;
        object?: serializers.ObjectType.Raw | null;
    }
}
