/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";
import { Usage } from "./Usage";
import { RankedDocument } from "./RankedDocument";
import { ObjectType } from "./ObjectType";

export const RerankingResponse: core.serialization.ObjectSchema<
    serializers.RerankingResponse.Raw,
    MixedbreadAI.RerankingResponse
> = core.serialization.object({
    usage: Usage,
    model: core.serialization.string(),
    data: core.serialization.list(RankedDocument),
    object: ObjectType.optional(),
    topK: core.serialization.property("top_k", core.serialization.number()),
    returnInput: core.serialization.property("return_input", core.serialization.boolean()),
});

export declare namespace RerankingResponse {
    interface Raw {
        usage: Usage.Raw;
        model: string;
        data: RankedDocument.Raw[];
        object?: ObjectType.Raw | null;
        top_k: number;
        return_input: boolean;
    }
}
