/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";

export const RerankingResponse: core.serialization.ObjectSchema<
    serializers.RerankingResponse.Raw,
    MixedbreadAI.RerankingResponse
> = core.serialization.object({
    usage: core.serialization.lazyObject(async () => (await import("..")).Usage),
    model: core.serialization.string(),
    data: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).RankedDocument)),
    object: core.serialization.lazy(async () => (await import("..")).ObjectType).optional(),
    topK: core.serialization.property("top_k", core.serialization.number()),
    returnInput: core.serialization.property("return_input", core.serialization.boolean()),
});

export declare namespace RerankingResponse {
    interface Raw {
        usage: serializers.Usage.Raw;
        model: string;
        data: serializers.RankedDocument.Raw[];
        object?: serializers.ObjectType.Raw | null;
        top_k: number;
        return_input: boolean;
    }
}
