/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";
export declare const RerankingResponse: core.serialization.ObjectSchema<serializers.RerankingResponse.Raw, MixedbreadAI.RerankingResponse>;
export declare namespace RerankingResponse {
    interface Raw {
        data: serializers.RankedDocument.Raw[];
        model: string;
        object?: serializers.ObjectType.Raw | null;
        return_input: boolean;
        top_k: number;
        usage: serializers.Usage.Raw;
    }
}
