/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";

export const TextDocument: core.serialization.ObjectSchema<serializers.TextDocument.Raw, MixedbreadAI.TextDocument> =
    core.serialization.object({
        text: core.serialization.string(),
    });

export declare namespace TextDocument {
    interface Raw {
        text: string;
    }
}
