/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const TextDocument: core.serialization.ObjectSchema<serializers.TextDocument.Raw, MixedbreadAiApi.TextDocument>;
export declare namespace TextDocument {
    interface Raw {
        text: string;
    }
}
