/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";

export const TooManyRequestsErrorBody: core.serialization.ObjectSchema<
    serializers.TooManyRequestsErrorBody.Raw,
    MixedbreadAI.TooManyRequestsErrorBody
> = core.serialization.object({
    type: core.serialization.stringLiteral("too_many_requests_error").optional(),
    url: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
    details: core.serialization.lazy(async () => (await import("..")).MxbaiApiErrorDetails).optional(),
});

export declare namespace TooManyRequestsErrorBody {
    interface Raw {
        type?: "too_many_requests_error" | null;
        url?: string | null;
        message?: string | null;
        details?: serializers.MxbaiApiErrorDetails.Raw | null;
    }
}
