/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const TooManyRequestsErrorBody: core.serialization.ObjectSchema<serializers.TooManyRequestsErrorBody.Raw, MixedbreadAiApi.TooManyRequestsErrorBody>;
export declare namespace TooManyRequestsErrorBody {
    interface Raw {
        type?: "too_many_requests_error" | null;
        url?: string | null;
        message?: string | null;
        details?: serializers.MxbaiWebErrorDetails.Raw | null;
    }
}
