/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";

export const TruncationStrategy: core.serialization.Schema<
    serializers.TruncationStrategy.Raw,
    MixedbreadAI.TruncationStrategy
> = core.serialization.enum_(["start", "end", "none"]);

export declare namespace TruncationStrategy {
    type Raw = "start" | "end" | "none";
}
