/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const TruncationStrategy: core.serialization.Schema<serializers.TruncationStrategy.Raw, MixedbreadAiApi.TruncationStrategy>;
export declare namespace TruncationStrategy {
    type Raw = "start" | "end" | "none";
}
