/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";
export declare const UnauthorizedErrorBody: core.serialization.ObjectSchema<serializers.UnauthorizedErrorBody.Raw, MixedbreadAI.UnauthorizedErrorBody>;
export declare namespace UnauthorizedErrorBody {
    interface Raw {
        type?: "unauthorized_error" | null;
        details?: serializers.MxbaiWebErrorDetails.Raw | null;
        message?: string | null;
        url?: string | null;
    }
}
