/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";

export const Usage: core.serialization.ObjectSchema<serializers.Usage.Raw, MixedbreadAI.Usage> =
    core.serialization.object({
        completionTokens: core.serialization.property("completion_tokens", core.serialization.number().optional()),
        promptTokens: core.serialization.property("prompt_tokens", core.serialization.number()),
        totalTokens: core.serialization.property("total_tokens", core.serialization.number()),
    });

export declare namespace Usage {
    interface Raw {
        completion_tokens?: number | null;
        prompt_tokens: number;
        total_tokens: number;
    }
}
