/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";

export const Usage: core.serialization.ObjectSchema<serializers.Usage.Raw, MixedbreadAI.Usage> =
    core.serialization.object({
        promptTokens: core.serialization.property("prompt_tokens", core.serialization.number()),
        totalTokens: core.serialization.property("total_tokens", core.serialization.number()),
        completionTokens: core.serialization.property("completion_tokens", core.serialization.number().optional()),
    });

export declare namespace Usage {
    interface Raw {
        prompt_tokens: number;
        total_tokens: number;
        completion_tokens?: number | null;
    }
}
