/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";
export declare const Usage: core.serialization.ObjectSchema<serializers.Usage.Raw, MixedbreadAI.Usage>;
export declare namespace Usage {
    interface Raw {
        completion_tokens?: number | null;
        prompt_tokens: number;
        total_tokens: number;
    }
}
