/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const Usage: core.serialization.ObjectSchema<serializers.Usage.Raw, MixedbreadAiApi.Usage>;
export declare namespace Usage {
    interface Raw {
        prompt_tokens: number;
        total_tokens: number;
        completion_tokens?: number | null;
    }
}
