/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const ValidationError: core.serialization.ObjectSchema<serializers.ValidationError.Raw, MixedbreadAiApi.ValidationError>;
export declare namespace ValidationError {
    type Raw = serializers.MxbaiWebError.Raw;
}
