/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";
import { MxbaiApiError } from "./MxbaiApiError";

export const ValidationError: core.serialization.ObjectSchema<
    serializers.ValidationError.Raw,
    MixedbreadAI.ValidationError
> = MxbaiApiError;

export declare namespace ValidationError {
    type Raw = MxbaiApiError.Raw;
}
