/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as MixedbreadAI from "../../api";
import * as core from "../../core";

export const ValidationError: core.serialization.ObjectSchema<
    serializers.ValidationError.Raw,
    MixedbreadAI.ValidationError
> = core.serialization.lazyObject(async () => (await import("..")).MxbaiApiError);

export declare namespace ValidationError {
    type Raw = serializers.MxbaiApiError.Raw;
}
