/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as MixedbreadAI from "../../api/index";
import * as core from "../../core";
import { MxbaiApiErrorDetails } from "./MxbaiApiErrorDetails";

export const WebTruncationError: core.serialization.ObjectSchema<
    serializers.WebTruncationError.Raw,
    MixedbreadAI.WebTruncationError
> = core.serialization.object({
    type: core.serialization.stringLiteral("truncation_error").optional(),
    url: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
    details: MxbaiApiErrorDetails.optional(),
});

export declare namespace WebTruncationError {
    interface Raw {
        type?: "truncation_error" | null;
        url?: string | null;
        message?: string | null;
        details?: MxbaiApiErrorDetails.Raw | null;
    }
}
