/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as MixedbreadAiApi from "../../api";
import * as core from "../../core";
export declare const WebTruncationError: core.serialization.ObjectSchema<serializers.WebTruncationError.Raw, MixedbreadAiApi.WebTruncationError>;
export declare namespace WebTruncationError {
    interface Raw {
        type?: "truncation_error" | null;
        url?: string | null;
        message?: string | null;
        details?: serializers.MxbaiWebErrorDetails.Raw | null;
    }
}
