/* tslint:disable */
/* eslint-disable */
/**
 * mixedbread-ai
 * Discover how to convert text into embeddings with the Embeddings API. Ideal for NLP tasks like text similarity and clustering. Use top open source models or your own fine-tuned models.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Embedding
 */
export interface Embedding {
    /**
     * The generated embeddings.
     * @type {Array<number>}
     * @memberof Embedding
     */
    embedding: Array<number>;
    /**
     * Index of the request text the embedding corresponds to.
     * @type {number}
     * @memberof Embedding
     */
    index: number;
    /**
     * Indicates if the text was truncated for the model.
     * @type {boolean}
     * @memberof Embedding
     */
    truncated?: boolean;
}

/**
 * Check if a given object implements the Embedding interface.
 */
export function instanceOfEmbedding(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "embedding" in value;
    isInstance = isInstance && "index" in value;

    return isInstance;
}

export function EmbeddingFromJSON(json: any): Embedding {
    return EmbeddingFromJSONTyped(json, false);
}

export function EmbeddingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Embedding {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'embedding': json['embedding'],
        'index': json['index'],
        'truncated': !exists(json, 'truncated') ? undefined : json['truncated'],
    };
}

export function EmbeddingToJSON(value?: Embedding | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'embedding': value.embedding,
        'index': value.index,
        'truncated': value.truncated,
    };
}

