/* tslint:disable */
/* eslint-disable */
/**
 * mixedbread-ai
 * Discover how to convert text into embeddings with the Embeddings API. Ideal for NLP tasks like text similarity and clustering. Use top open source models or your own fine-tuned models.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Embeddings200ResponseUsage
 */
export interface Embeddings200ResponseUsage {
    /**
     * The number of prompt tokens used.
     * @type {number}
     * @memberof Embeddings200ResponseUsage
     */
    promptTokens?: number;
    /**
     * The total number of tokens used.
     * @type {number}
     * @memberof Embeddings200ResponseUsage
     */
    totalTokens?: number;
}

/**
 * Check if a given object implements the Embeddings200ResponseUsage interface.
 */
export function instanceOfEmbeddings200ResponseUsage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Embeddings200ResponseUsageFromJSON(json: any): Embeddings200ResponseUsage {
    return Embeddings200ResponseUsageFromJSONTyped(json, false);
}

export function Embeddings200ResponseUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Embeddings200ResponseUsage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'promptTokens': !exists(json, 'prompt_tokens') ? undefined : json['prompt_tokens'],
        'totalTokens': !exists(json, 'total_tokens') ? undefined : json['total_tokens'],
    };
}

export function Embeddings200ResponseUsageToJSON(value?: Embeddings200ResponseUsage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prompt_tokens': value.promptTokens,
        'total_tokens': value.totalTokens,
    };
}

