/* tslint:disable */
/* eslint-disable */
/**
 * mixedbread-ai
 * Discover how to convert text into embeddings with the Embeddings API. Ideal for NLP tasks like text similarity and clustering. Use top open source models or your own fine-tuned models.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmbeddingsResponseDataInner
 */
export interface EmbeddingsResponseDataInner {
    /**
     * The generated embeddings.
     * @type {Array<number>}
     * @memberof EmbeddingsResponseDataInner
     */
    embedding?: Array<number>;
    /**
     * Index of the request text the embedding corresponds to.
     * @type {number}
     * @memberof EmbeddingsResponseDataInner
     */
    index?: number;
    /**
     * Indicates if the text was truncated for the model.
     * @type {boolean}
     * @memberof EmbeddingsResponseDataInner
     */
    truncated?: boolean;
}

/**
 * Check if a given object implements the EmbeddingsResponseDataInner interface.
 */
export function instanceOfEmbeddingsResponseDataInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EmbeddingsResponseDataInnerFromJSON(json: any): EmbeddingsResponseDataInner {
    return EmbeddingsResponseDataInnerFromJSONTyped(json, false);
}

export function EmbeddingsResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddingsResponseDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'embedding': !exists(json, 'embedding') ? undefined : json['embedding'],
        'index': !exists(json, 'index') ? undefined : json['index'],
        'truncated': !exists(json, 'truncated') ? undefined : json['truncated'],
    };
}

export function EmbeddingsResponseDataInnerToJSON(value?: EmbeddingsResponseDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'embedding': value.embedding,
        'index': value.index,
        'truncated': value.truncated,
    };
}

