/* tslint:disable */
/* eslint-disable */
/**
 * mixedbread-ai
 * Discover how to convert text into embeddings with the Embeddings API. Ideal for NLP tasks like text similarity and clustering. Use top open source models or your own fine-tuned models.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelUsage } from './ModelUsage';
import {
    ModelUsageFromJSON,
    ModelUsageFromJSONTyped,
    ModelUsageToJSON,
} from './ModelUsage';

/**
 * 
 * @export
 * @interface ModelBaseResponse
 */
export interface ModelBaseResponse {
    /**
     * The embeddings model used.
     * @type {string}
     * @memberof ModelBaseResponse
     */
    model: string;
    /**
     * 
     * @type {ModelUsage}
     * @memberof ModelBaseResponse
     */
    usage: ModelUsage;
}

/**
 * Check if a given object implements the ModelBaseResponse interface.
 */
export function instanceOfModelBaseResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "model" in value;
    isInstance = isInstance && "usage" in value;

    return isInstance;
}

export function ModelBaseResponseFromJSON(json: any): ModelBaseResponse {
    return ModelBaseResponseFromJSONTyped(json, false);
}

export function ModelBaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelBaseResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'model': json['model'],
        'usage': ModelUsageFromJSON(json['usage']),
    };
}

export function ModelBaseResponseToJSON(value?: ModelBaseResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'model': value.model,
        'usage': ModelUsageToJSON(value.usage),
    };
}

