/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const MixedbreadAiApiEnvironment: {
    readonly Default: "https://api.mixedbread.ai";
};
export declare type MixedbreadAiApiEnvironment = typeof MixedbreadAiApiEnvironment.Default;
