/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const MixedbreadAIEnvironment: {
    readonly Default: "https://api.mixedbread.ai";
};
export declare type MixedbreadAIEnvironment = typeof MixedbreadAIEnvironment.Default;
