/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const MixedbreadAIEnvironment = {
    Default: "https://api.mixedbread.ai",
} as const;

export type MixedbreadAIEnvironment = typeof MixedbreadAIEnvironment.Default;
