"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MixedbreadAIEnvironment = void 0;
exports.MixedbreadAIEnvironment = {
    Default: "https://api.mixedbread.ai",
};
